x-app-environment: &app_environment
  DJANGO_LOG_LEVEL: ${DJANGO_LOG_LEVEL:-INFO}
  DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY:-?DJANGO_SECRET_KEY environment variable is required}
  DJANGO_ALLOWED_HOSTS: localhost,127.0.0.1,172.16.0.0/12,${DOMAINS}
  DJANGO_CSRF_TRUSTED_ORIGINS: ${CSRF_TRUSTED_ORIGINS:-${DOMAINS}}
  DJANGO_DATABASE_URL: postgres://${POSTGRES_USER:-django}:${POSTGRES_PASSWORD:-?POSTGRES_PASSWORD environment variable is required}@postgres:5432/${POSTGRES_DB:-django}
  DJANGO_CACHE_URL: redis://:${VALKEY_PASSWORD:-?VALKEY_PASSWORD environment variable is required}@valkey:6379/0
  GRANIAN_WORKERS: ${GRANIAN_WORKERS:-2}

services:
  app:
    image: ${IMAGE_NAME}:${IMAGE_TAG}
    depends_on:
      postgres:
        condition: service_healthy
      valkey:
        condition: service_healthy
    command:
      - sh
      - -c
      - |
        python manage.py migrate
        exec granian \
          --interface asgi \
          --host 0.0.0.0 \
          --respawn-failed-workers \
          --static-path-route /static \
          --static-path-mount ./staticfiles \
          --static-path-route /media \
          --static-path-mount ./media \
          config.asgi:application
    environment: *app_environment
    restart: unless-stopped

  postgres:
    image: postgres:18.4-trixie@sha256:7aba8c66107ee218ddbaacb30eae46d774bf5e34ab77a917be819b4e227493c4
    volumes:
      - database:/var/lib/postgresql
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-django}
      POSTGRES_USER: ${POSTGRES_USER:-django}
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD:-?POSTGRES_PASSWORD environment variable is required}"
    restart: unless-stopped
    healthcheck:
      test: [
        "CMD-SHELL",
        "pg_isready -U ${POSTGRES_USER:-django} -d ${POSTGRES_DB:-django}",
      ]
      interval: 5s
      timeout: 5s
      retries: 5

  valkey:
    image: valkey/valkey:9.1.0-trixie@sha256:4963247afc4cd33c7d3b2d2816b9f7f8eeebab148d29056c2ca4d7cbc966f2d9
    restart: unless-stopped
    command: valkey-server --requirepass ${VALKEY_PASSWORD:-?VALKEY_PASSWORD environment variable is required}
    healthcheck:
      test: ["CMD", "valkey-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  database:
